package com.walmart.surendra.ticketingService.enums;

/**
 * Created by Surendra Raut on 11/30/2017.
 */
public enum TicketingServiceError {
    LOCKING_INTERRUPTED,
    UNEXPECTED,
    INVALID_NUM_SEATS,
    EMPTY_EMAIL_ID,
    INVALID_EMAIL_ID,
    INSUFFICIENT_SEATS_AVAILABLE,
    CUST_EMAIL_ID_IN_USE,
    INVALID_SEATHOLD_ID,
    SEATHOLD_ID_MATCH_EMAIL_MISMATCH,
    SEATHOLD_ID_ALREADY_RESERVED,
    SEATHOLD_ID_EXPIRED,
    SEATHOLD_ID_EXPIRED_OR_RESERVED,
    ERROR_ID_NOT_FOUND,
    LOCKING_TIMED_OUT,
    UNLOCK_FAILED
}
